#bridge-file-version: #5
scoreboard objectives add binIn dummy "이진법 입력"
scoreboard objectives add binCopy dummy "이진법 입력 Copy"
scoreboard objectives add binCopyBit dummy "이진법 입력 CopyBit"
scoreboard objectives add binBit1 dummy "이진법 변환 결과:1비트"
scoreboard objectives add binBit2 dummy "이진법 변환 결과:2비트"
scoreboard objectives add binBit3 dummy "이진법 변환 결과:3비트"
scoreboard objectives add binBit4 dummy "이진법 변환 결과:4비트"
scoreboard objectives add binBit5 dummy "이진법 변환 결과:5비트"
scoreboard objectives add binBit6 dummy "이진법 변환 결과:6비트"
scoreboard objectives add binBit7 dummy "이진법 변환 결과:7비트"
scoreboard objectives add binBit8 dummy "이진법 변환 결과:8비트"
scoreboard objectives add binBit9 dummy "이진법 변환 결과:9비트"
scoreboard objectives add binBit10 dummy "이진법 변환 결과:10비트"
scoreboard objectives add binBit11 dummy "이진법 변환 결과:11비트"
scoreboard objectives add binBit12 dummy "이진법 변환 결과:12비트"
scoreboard objectives add binBit13 dummy "이진법 변환 결과:13비트"
scoreboard objectives add binBit14 dummy "이진법 변환 결과:14비트"
scoreboard objectives add binBit15 dummy "이진법 변환 결과:15비트"
scoreboard objectives add binBit16 dummy "이진법 변환 결과:16비트"
scoreboard objectives add binBit17 dummy "이진법 변환 결과:17비트"
scoreboard objectives add binBit18 dummy "이진법 변환 결과:18비트"
scoreboard objectives add binBit19 dummy "이진법 변환 결과:19비트"
scoreboard objectives add binBit20 dummy "이진법 변환 결과:20비트"
scoreboard objectives add binBit21 dummy "이진법 변환 결과:21비트"
scoreboard objectives add binBit22 dummy "이진법 변환 결과:22비트"
scoreboard objectives add binBit23 dummy "이진법 변환 결과:23비트"
scoreboard objectives add binBit24 dummy "이진법 변환 결과:24비트"
scoreboard objectives add binBit25 dummy "이진법 변환 결과:25비트"
scoreboard objectives add binBit26 dummy "이진법 변환 결과:26비트"
scoreboard objectives add binBit27 dummy "이진법 변환 결과:27비트"
scoreboard objectives add binBit28 dummy "이진법 변환 결과:28비트"
scoreboard objectives add binBit29 dummy "이진법 변환 결과:29비트"
scoreboard objectives add binBit30 dummy "이진법 변환 결과:30비트"
scoreboard objectives add binBit31 dummy "이진법 변환 결과:31비트"
scoreboard objectives add binBit32 dummy "이진법 변환 결과:32비트"
scoreboard objectives add numLib dummy "숫자 라이브러리"
scoreboard players set two numLib 2
tellraw @a {"rawtext":[{"text":"§a[이진법] §r세팅 완료! binIn에 점수를 넣어서 변환시켜보세요!"}]}
tellraw @a {"rawtext":[{"text":"§a[이진법] §c단, 음수를 입력할 시 오류가 §l§4반드시 §r§c발생합니다."}]}